services:
  app:
    user: "${USER_ID:-1000}"
    hostname: "${HOST_NAME:-danbm}"
    image: cybulde-data-processing
    container_name: cybulde-data-processing-container
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./creds/cybulde-428517-5c9798ea84c5.json
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        USER_NAME: "${USER_NAME:-danbm}"
        USER_ID: "${USER_ID:-1000}"
    volumes:
      - ./:/app/
      - ~/.config/gcloud/:/home/${USER_NAME}/.config/gcloud
    ports:
      # To use Jupyter Lab must be port 8888
      - "8888:8888"

    ipc: host
    init: true
