defaults:
  - jtc_dataset_reader_schema

# data_local_save_dir comes from data_processing_config_schema.py
dataset_dir: ${data_local_save_dir}/jigsaw-toxic-comment
dataset_name: jtc
dev_split_ratio: 0.03
