defaults:
  - twitter_dataset_reader_schema

# data_local_save_dir comes from data_processing_config_schema.py
dataset_dir: ${data_local_save_dir}/twitter
dataset_name: twitter
test_split_ratio: 0.1
dev_split_ratio: 0.125
